### ISSUE TITLE
use pyproject.toml?

### ISSUE THREAD

**Issue by jcbhmr** [jcbhmr/bikeshed-builder#7]
https://stackoverflow.com/questions/62408719/download-dependencies-declared-in-pyproject-toml-using-pip

```toml
dependencies = [
    "pyaedt==0.4.7",
    "Django==3.2.8",
]
```

```sh
pip install .
```
